import type { Metadata } from "next";
import { Raleway, Funnel_Display } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { Footer } from "@/components/Footer";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${raleway.variable} ${funnelDisplay.variable}`}
      >
        <Providers>
          <FloatingNav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
